### PR TITLE
feat: Added Binary Trees in the DSA

### LINKED ISSUE #3623: Binary Tree missing in DSA.

### PR DESCRIPTION
**Pull request by kalkeshwar**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [x] ✨ Feature
- [x] 🌟 stared the repo
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
fixes #3623
added the binary Trees concepts and solution in the DSA and also added name in the contributers.md

### CODE REVIEW

**Comment by kalkeshwar** [comment]
I have made a pull request which fixes #3623(adding binary trees in the DSA)

**Comment by kalkeshwar** [comment]
Hi @keshavsingh4522 ,
I hope you're doing well. I noticed that my pull request #4523 is still open and awaiting review. Although the related issue has been closed, I believe this PR addresses the problem effectively.
Could you please take some time to review and merge it when you have a chance? I'd appreciate your feedback and help with this.
Thank you in advance for your time and consideration.

**Comment by kalkeshwar** [comment]
Hi @keshavsingh4522 ,
please review and merge my pull request #4523 which resolves issue and update the things.
Thanks for your time and consideration in advance.

**Comment by kalkeshwar** [comment]
@keshavsingh4522  , You closed the issue but the PR #4523 has not merged yet . If you have any feedback or if there's anything I can do to assist with the review process, please let me know.

**Comment by keshavsingh3197** [comment]
@kalkeshwar , pr merged.

**Pull request merged**
